const mongoose = require("mongoose");

const hotelCollection = new mongoose.Schema({
  _id: String,
  hotelID: Number,
  images: [
    {
      url: String,
    },
  ],
  title: String,
  ratings: String,
  ratings_no: String,
  location: String,
  sub_title: String,
  guests: String,
  beds: [Boolean],
  bedrooms: [Boolean],
  bathrooms: [Boolean],
  description_short: String,
  the_space: String,
  guest_access: String,
  guest_access_points: [String],
  other: String,
  amenities: {
    lift: Boolean,
    ac: Boolean,
    wifi: Boolean,
    parking: Boolean,
    laptop: Boolean,
    disabled: Boolean,
    tv: Boolean,
    infant: Boolean,
  },
  amenities_basic: [String],
  amenities_facilities: [String],
  amenities_dining: [String],
  amenities_bb: [String],
  amenities_safety: [String],
  amenities_notincluded: [String],
  rating_cleanliness: String,
  rating_checkin: String,
  rating_communication: String,
  rating_accuracy: String,
  rating_Loaction: String,
  rating_value: String,
  reviews: [
    {
      name: String,
      dated: String,
      review: String,
    },
  ],
  sitter_name: String,
  sitter_description: String,
  sitter_mail: String,
  sitter_phone: String,
  sitter_care: String,
  sitter_value: String,
  sitter_knowledge: String,
  sitter_images: [
    {
      url: String,
    },
  ],
  sitter_available: [Boolean],
  spa_name: String,
  spa_images: [
    {
      url: String,
    },
  ],
  sap_services: [String],
  spa_mail: String,
  spa_phone: String,
  spa_care: String,
  spa_value: String,
  spa_quality: String,
  spa_available: [Boolean],
  map_description_short: String,
  map_description_getting_around: String,
  ppn: String,
  service_fee: String,
  taxes: String,
  spa_cost: String,
  sitter_cost: String,
  host_phone: String,
  host_mail: String,
  latitude: String,
  longitude: String,
  type: String,
});

module.exports = hotelCollection;
